#!/usr/bin/env bash
mkdir -p bin
echo "#!/usr/bin/env node" > ./bin/cli.js
npx lsc -cp --no-header ./src/cli.ls >> ./bin/cli.js
chmod 755 ./bin/cli.js
npx lsc -cp --no-header ./src/index.ls >> ./bin/index.js
